INSERT INTO categories (slug, name, display_order) VALUES
  ('foundation-models',  'Foundation Models',   10),
  ('agent-framework',    'Agent Framework',     20),
  ('llm-framework',      'LLM Framework',       30),
  ('mcp',                'MCP',                 40),
  ('rag',                'RAG',                 50),
  ('vector-database',    'Vector Database',     60),
  ('knowledge-graph',    'Knowledge Graph',     70),
  ('ai-ide',             'AI IDE',              80),
  ('ai-coding',          'AI Coding',           90),
  ('ai-evaluation',      'AI Evaluation',      100),
  ('ai-observability',   'AI Observability',   110),
  ('ai-security',        'AI Security',        120),
  ('ai-infrastructure',  'AI Infrastructure',  130),
  ('ai-deployment',      'AI Deployment',      140),
  ('ai-serving',         'AI Serving',         150),
  ('inference',          'Inference',          160),
  ('mlops',              'MLOps',              170),
  ('llmops',             'LLMOps',             180),
  ('fine-tuning',        'Fine-tuning',        190),
  ('synthetic-data',     'Synthetic Data',     200),
  ('dataset',            'Dataset',            210),
  ('computer-vision',    'Computer Vision',    220),
  ('nlp',                'NLP',                230),
  ('speech-voice',       'Speech & Voice',     240),
  ('robotics',           'Robotics',           250),
  ('other-ai',           'Other AI',           900)
ON CONFLICT (slug) DO NOTHING;
